from tkinter import *

Calculadora = Tk()

# Tamanhos dos botões(Button)
Calculadora.grid_rowconfigure(0, weight=1)
Calculadora.grid_columnconfigure(0, weight=1)
Calculadora.grid_rowconfigure(1, weight=1)
Calculadora.grid_columnconfigure(1, weight=1)
Calculadora.grid_columnconfigure(2, weight=1)

# widgets
label1 = Label(Calculadora)
bt1 = Button(Calculadora, text='7', font='Arial 30')
bt2 = Button(Calculadora, text='8', font='Arial 30')
bt3 = Button(Calculadora, text='9', font='Arial 30')
bt4 = Button(Calculadora, text='*', font='Arial 30')
bt5 = Button(Calculadora, text='4', font='Arial 30')
bt6 = Button(Calculadora, text='5', font='Arial 30')
bt7 = Button(Calculadora, text='6', font='Arial 30')
bt8 = Button(Calculadora, text='/', font='Arial 30')
bt9 = Button(Calculadora, text='1', font='Arial 30')
bt10 = Button(Calculadora, text='2', font='Arial 30')
bt11 = Button(Calculadora, text='3', font='Arial 30')
bt12 = Button(Calculadora, text='+', font='Arial 30')
bt13 = Button(Calculadora, text='0', font='Arial 30')
bt14 = Button(Calculadora, text='=', font='Arial 30')
bt15 = Button(Calculadora, text='.', font='Arial 30')
bt16 = Button(Calculadora, text='-', font='Arial 30')
bt17 = Button(Calculadora, text='Del', font='Arial 30')
bt18 = Button(Calculadora, text='C', font='Arial 30')
bt19 = Button(Calculadora, text='(', font='Arial 30')
bt20 = Button(Calculadora, text=')', font='Arial 30')

# layout
label1.grid(row=0, column=0, sticky=NSEW)
bt1.grid(row=1, column=0, sticky=NSEW)
bt2.grid(row=1, column=1, sticky=NSEW)
bt3.grid(row=1, column=2, sticky=NSEW)
bt4.grid(row=1, column=3, sticky=NSEW)
bt5.grid(row=2, column=0, sticky=NSEW)
bt6.grid(row=2, column=1, sticky=NSEW)
bt7.grid(row=2, column=2, sticky=NSEW)
bt8.grid(row=2, column=3, sticky=NSEW)
bt9.grid(row=3, column=0, sticky=NSEW)
bt10.grid(row=3, column=1, sticky=NSEW)
bt11.grid(row=3, column=2, sticky=NSEW)
bt12.grid(row=3, column=3, sticky=NSEW)
bt13.grid(row=4, column=0, sticky=NSEW)
bt14.grid(row=4, column=1, sticky=NSEW)
bt15.grid(row=4, column=2, sticky=NSEW)
bt16.grid(row=4, column=3, sticky=NSEW)
bt17.grid(row=5, column=0, sticky=NSEW)
bt18.grid(row=5, column=1, sticky=NSEW)
bt19.grid(row=5, column=2, sticky=NSEW)
bt20.grid(row=5, column=3, sticky=NSEW)

# run
Calculadora.mainloop()